#!/usr/bin/env python3
"""Extract conservative copy candidates from an evidence package."""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


AMBIGUOUS_LABELS = {"open", "continue", "done", "photos", "next", "back", "close"}
COPY_LABEL_PATTERNS = [
    "文案",
    "copy",
    "文案内容",
    "展示文案",
    "按钮文案",
    "toast文案",
    "toast提示",
    "提示文案",
    "错误文案",
    "弹窗文案",
    "标题",
    "副标题",
    "按钮",
    "button text",
    "cta",
    "title",
    "subtitle",
    "message",
    "label",
]
SCREEN_LABEL_PATTERNS = ["页面", "screen", "page", "route", "tab", "弹窗", "模块"]
BACKGROUND_LABEL_PATTERNS = ["背景", "场景", "说明", "context", "description", "when", "触发", "shown when"]
INTENT_LABEL_PATTERNS = ["意图", "intent", "purpose", "action"]
COMPONENT_LABEL_PATTERNS = ["组件", "控件", "component", "type", "类型"]
TARGET_LOCALE_LABEL_PATTERNS = ["目标语种", "支持语言", "发布语种", "多语言范围", "target locales", "languages"]
TARGET_OUTPUT_LABEL_PATTERNS = ["目标端", "交付端", "输出格式", "target outputs", "platforms", "delivery formats"]

FIELD_ALIASES = {
    "key": ["key", "name", "string_name"],
    "source_text": ["source_text", "source", "original_text", "english", "en", "原文", "文案", "copy", "展示文案"],
    "screen": ["screen", "page", "route", "页面", "tab"],
    "component": ["component", "ui_component", "控件", "组件", "类型"],
    "intent": ["intent", "purpose", "文案意图", "意图"],
    "background": ["background", "context", "description", "scene", "背景说明", "场景", "说明"],
    "risk_level": ["risk_level", "risk", "风险等级"],
    "owner": ["owner", "reviewer", "业务owner"],
    "length_limit": ["length_limit", "char_limit", "长度限制"],
    "placeholders": ["placeholders", "variables", "占位符"],
    "message_format": ["message_format", "format", "消息格式"],
}

LOCALE_TOKENS = {
    "简体中文": "zh-Hans",
    "简中": "zh-Hans",
    "zh-hans": "zh-Hans",
    "zh-cn": "zh-Hans",
    "繁体中文": "zh-Hant",
    "繁中": "zh-Hant",
    "zh-hant": "zh-Hant",
    "zh-tw": "zh-Hant",
    "中文": "zh-Hans",
    "英文": "en",
    "英语": "en",
    "english": "en",
    "en": "en",
    "德语": "de",
    "german": "de",
    "de": "de",
    "法语": "fr",
    "french": "fr",
    "fr": "fr",
    "意大利语": "it",
    "italian": "it",
    "it": "it",
    "西班牙语": "es",
    "spanish": "es",
    "es": "es",
    "葡萄牙语": "pt",
    "巴西葡萄牙语": "pt-BR",
    "葡语": "pt",
    "portuguese": "pt",
    "brazilian portuguese": "pt-BR",
    "pt-br": "pt-BR",
    "俄语": "ru",
    "russian": "ru",
    "ru": "ru",
    "韩语": "ko",
    "korean": "ko",
    "ko": "ko",
    "印地语": "hi",
    "hindi": "hi",
    "hi": "hi",
}

OUTPUT_TOKENS = {
    "ios": "ios",
    "iphone": "ios",
    "android": "android",
    "web": "json",
    "app json": "json",
    "json": "json",
    "csv": "csv",
    "manifest": "manifest",
}

COPY_ONLY_HEADING_PATTERNS = ["文案", "copy", "toast", "按钮", "title", "subtitle", "message", "提示"]
GENERIC_HEADINGS = {"需求背景", "prd", "说明", "背景", "details", "overview"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Extract copy candidates from an evidence package.")
    parser.add_argument("source", help="Path to evidence.json generated by ingest_artifacts.py")
    parser.add_argument("--output", required=True, help="Output path for the copy candidates JSON.")
    return parser.parse_args()


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def slugify(value: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]+", "_", value.strip().lower()).strip("_")


def normalize_text(value: Any) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def field_lookup(fields: dict[str, Any], target: str) -> str:
    aliases = FIELD_ALIASES.get(target, [])
    lowered = {str(key).strip().lower(): value for key, value in fields.items() if key is not None}
    for alias in aliases:
        if alias.lower() in lowered and normalize_text(lowered[alias.lower()]):
            return normalize_text(lowered[alias.lower()])
    return ""


def looks_copy_label(label: str) -> bool:
    lowered = label.strip().lower()
    return any(token in lowered for token in COPY_LABEL_PATTERNS)


def looks_screen_label(label: str) -> bool:
    lowered = label.strip().lower()
    return any(token in lowered for token in SCREEN_LABEL_PATTERNS)


def looks_background_label(label: str) -> bool:
    lowered = label.strip().lower()
    return any(token in lowered for token in BACKGROUND_LABEL_PATTERNS)


def looks_intent_label(label: str) -> bool:
    lowered = label.strip().lower()
    return any(token in lowered for token in INTENT_LABEL_PATTERNS)


def looks_component_label(label: str) -> bool:
    lowered = label.strip().lower()
    return any(token in lowered for token in COMPONENT_LABEL_PATTERNS)


def looks_target_locale_label(label: str) -> bool:
    lowered = label.strip().lower()
    return any(token in lowered for token in TARGET_LOCALE_LABEL_PATTERNS)


def looks_target_output_label(label: str) -> bool:
    lowered = label.strip().lower()
    return any(token in lowered for token in TARGET_OUTPUT_LABEL_PATTERNS)


def infer_component(label: str, heading_hint: str = "") -> str:
    lowered = f"{label} {heading_hint}".lower()
    if "toast" in lowered:
        return "toast"
    if "dialog" in lowered or "弹窗" in lowered or "modal" in lowered:
        return "dialog"
    if "error" in lowered or "错误" in lowered:
        return "error_message"
    if "subtitle" in lowered or "副标题" in lowered:
        return "subtitle"
    if "title" in lowered or "标题" in lowered:
        return "title"
    if "tab" in lowered:
        return "tab_label"
    if "banner" in lowered:
        return "banner"
    if "button" in lowered or "cta" in lowered or "按钮" in lowered:
        return "button"
    if "label" in lowered:
        return "label"
    return ""


def parse_length_limit(raw: str) -> dict[str, Any] | None:
    value = normalize_text(raw)
    if not value:
        return None
    digits = re.search(r"(\d+)", value)
    if digits:
        mode = "strict" if any(token in value.lower() for token in ["strict", "严格", "max", "最多"]) else "short"
        return {"mode": mode, "max_chars": int(digits.group(1))}
    return {"mode": value}


def parse_placeholders(raw: str) -> list[dict[str, Any]]:
    value = normalize_text(raw)
    if not value:
        return []
    names = re.findall(r"\{([a-zA-Z0-9_]+)\}", value)
    if not names:
        names = [token.strip() for token in re.split(r"[,，/]+", value) if token.strip()]
    return [{"name": name, "canonical": f"{{{name}}}"} for name in names]


def parse_locale_hints(value: str) -> list[str]:
    tokens = re.split(r"[,，/、;\s]+", normalize_text(value).lower())
    locales: list[str] = []
    for token in tokens:
        if not token:
            continue
        locale = LOCALE_TOKENS.get(token)
        if locale and locale not in locales:
            locales.append(locale)
    return locales


def parse_output_hints(value: str) -> list[str]:
    text = normalize_text(value).lower()
    outputs: list[str] = []
    for token, target in OUTPUT_TOKENS.items():
        if token in text and target not in outputs:
            outputs.append(target)
    return outputs


def looks_heading_copy_related(text: str) -> bool:
    lowered = normalize_text(text).lower()
    return any(token in lowered for token in COPY_ONLY_HEADING_PATTERNS)


def pick_screen_from_headings(headings: list[str]) -> str:
    for heading in reversed(headings):
        clean = normalize_text(heading)
        if not clean or clean in GENERIC_HEADINGS or looks_heading_copy_related(clean):
            continue
        return clean
    return ""


def looks_visible_copy(text: str) -> bool:
    value = normalize_text(text)
    if not value or len(value) > 140:
        return False
    if re.search(r"[。；;]{2,}", value):
        return False
    if any(token in value.lower() for token in ["需求", "背景", "因为", "如果用户", "用户可以", "should", "must", "flow", "步骤"]):
        return False
    return True


def quoted_copy_candidates(text: str) -> list[str]:
    return [normalize_text(match) for match in re.findall(r"[\"“](.+?)[\"”]", text) if looks_visible_copy(match)]


def evidence_from_block(artifact: dict[str, Any], block: dict[str, Any]) -> dict[str, Any]:
    images = list(block.get("image_refs") or [])
    payload = {
        "extraction_mode": artifact.get("extraction_mode") or "structured-text",
        "confidence": artifact.get("source_confidence") or "medium",
        "verified_text": bool(artifact.get("text_available")),
        "artifacts": [
            {
                "kind": artifact.get("kind"),
                "path": artifact.get("path"),
                "artifact_id": artifact.get("artifact_id"),
                "block_id": block.get("block_id"),
                "location": block.get("location", {}),
                "image_refs": images,
            }
        ],
    }
    return payload


def candidate_key(entry: dict[str, Any]) -> tuple[str, str, str, str]:
    return (
        normalize_text(entry.get("source_text")).lower(),
        normalize_text(entry.get("screen")).lower(),
        normalize_text(entry.get("component")).lower(),
        normalize_text(entry.get("background")).lower(),
    )


def merge_candidate(bucket: dict[tuple[str, str, str, str], dict[str, Any]], entry: dict[str, Any]) -> None:
    key = candidate_key(entry)
    existing = bucket.get(key)
    if not existing:
        bucket[key] = entry
        return
    existing_artifacts = existing.setdefault("source_evidence", {}).setdefault("artifacts", [])
    new_artifacts = entry.get("source_evidence", {}).get("artifacts", [])
    for artifact in new_artifacts:
        if artifact not in existing_artifacts:
            existing_artifacts.append(artifact)
    if not existing.get("screenshot_ref") and entry.get("screenshot_ref"):
        existing["screenshot_ref"] = entry["screenshot_ref"]


def build_candidate(
    source_text: str,
    artifact: dict[str, Any],
    block: dict[str, Any],
    context: dict[str, str],
    label_hint: str = "",
) -> dict[str, Any]:
    component = context.get("component") or infer_component(label_hint, context.get("heading_hint", ""))
    background = context.get("background", "")
    intent = context.get("intent", "")
    screen = context.get("screen", "")
    image_refs = block.get("image_refs") or []
    payload: dict[str, Any] = {
        "source_text": normalize_text(source_text),
        "screen": screen,
        "component": component,
        "intent": intent,
        "background": background,
        "source_evidence": evidence_from_block(artifact, block),
    }
    if image_refs:
        payload["screenshot_ref"] = image_refs[0]
    return payload


def update_context_from_label(context: dict[str, str], label: str, value: str) -> None:
    clean = normalize_text(value)
    if looks_screen_label(label):
        context["screen"] = clean
    elif looks_background_label(label):
        context["background"] = clean
    elif looks_intent_label(label):
        context["intent"] = clean
    elif looks_component_label(label):
        context["component"] = clean


def infer_structured_candidate(block: dict[str, Any], artifact: dict[str, Any], context: dict[str, str]) -> dict[str, Any] | None:
    fields = block.get("fields")
    if not isinstance(fields, dict):
        return None
    source_text = field_lookup(fields, "source_text")
    header_hint = ""
    if not source_text:
        for key, value in fields.items():
            if looks_copy_label(str(key)):
                source_text = normalize_text(value)
                header_hint = str(key)
                break
    if not looks_visible_copy(source_text):
        return None

    screen = field_lookup(fields, "screen") or context.get("screen", "")
    component = field_lookup(fields, "component") or infer_component(header_hint or block.get("type", ""), context.get("heading_hint", ""))
    intent = field_lookup(fields, "intent") or context.get("intent", "")
    background = field_lookup(fields, "background") or context.get("background", "")
    payload = build_candidate(
        source_text,
        artifact,
        block,
        {
            "screen": screen,
            "component": component,
            "intent": intent,
            "background": background,
            "heading_hint": context.get("heading_hint", ""),
        },
        header_hint,
    )
    key_value = field_lookup(fields, "key")
    if key_value:
        payload["key"] = key_value
    risk_level = field_lookup(fields, "risk_level")
    if risk_level:
        payload["risk_level"] = risk_level
    owner = field_lookup(fields, "owner")
    if owner:
        payload["owner"] = owner
    length_limit = parse_length_limit(field_lookup(fields, "length_limit"))
    if length_limit:
        payload["length_limit"] = length_limit
    placeholders = parse_placeholders(field_lookup(fields, "placeholders"))
    if placeholders:
        payload["placeholders"] = placeholders
        payload["message_format"] = field_lookup(fields, "message_format") or "named-template"
    return payload


def infer_candidate_from_text(
    block: dict[str, Any],
    artifact: dict[str, Any],
    context: dict[str, str],
) -> tuple[list[dict[str, Any]], list[str], list[str]]:
    text = normalize_text(block.get("text"))
    if not text:
        return [], [], []

    locales: list[str] = []
    outputs: list[str] = []
    entries: list[dict[str, Any]] = []

    heading_hint = context.get("heading_hint", "")
    if looks_target_locale_label(heading_hint):
        locales = parse_locale_hints(text)
        if locales:
            return [], locales, []
    if looks_target_output_label(heading_hint):
        outputs = parse_output_hints(text)
        if outputs:
            return [], [], outputs

    label_match = re.match(r"^(?P<label>[^:：]{1,40})[:：]\s*(?P<value>.+)$", text)
    if label_match:
        label = label_match.group("label").strip()
        value = label_match.group("value").strip()
        if looks_target_locale_label(label):
            locales = parse_locale_hints(value)
            return [], locales, []
        if looks_target_output_label(label):
            outputs = parse_output_hints(value)
            return [], [], outputs
        if looks_copy_label(label) and looks_visible_copy(value):
            component = context.get("component") or infer_component(label, context.get("heading_hint", ""))
            entries.append(
                build_candidate(
                    value,
                    artifact,
                    block,
                    {
                        "screen": context.get("screen", ""),
                        "component": component,
                        "intent": context.get("intent", ""),
                        "background": context.get("background", ""),
                        "heading_hint": context.get("heading_hint", ""),
                    },
                    label,
                )
            )
            return entries, [], []
        update_context_from_label(context, label, value)
        return [], [], []

    for quoted in quoted_copy_candidates(text):
        if any(token in text.lower() for token in ["展示文案", "copy", "按钮", "toast", "title", "subtitle", "显示", "文案为"]):
            entries.append(
                build_candidate(
                    quoted,
                    artifact,
                    block,
                    {
                        "screen": context.get("screen", ""),
                        "component": context.get("component") or infer_component(text, context.get("heading_hint", "")),
                        "intent": context.get("intent", ""),
                        "background": context.get("background", ""),
                        "heading_hint": context.get("heading_hint", ""),
                    },
                    text,
                )
            )
    if entries:
        return entries, [], []

    if block.get("type") == "list-item" and looks_heading_copy_related(context.get("heading_hint", "")) and looks_visible_copy(text):
        entries.append(
            build_candidate(
                text,
                artifact,
                block,
                {
                    "screen": context.get("screen", ""),
                    "component": context.get("component") or infer_component(context.get("heading_hint", ""), ""),
                    "intent": context.get("intent", ""),
                    "background": context.get("background", ""),
                    "heading_hint": context.get("heading_hint", ""),
                },
                context.get("heading_hint", ""),
            )
        )
    return entries, [], []


def extract_from_artifact(artifact: dict[str, Any]) -> tuple[list[dict[str, Any]], list[str], list[str]]:
    blocks = sorted(artifact.get("blocks", []), key=lambda block: str(block.get("block_id")))
    heading_stack: list[str] = []
    context = {"screen": "", "component": "", "intent": "", "background": "", "heading_hint": ""}
    entries: list[dict[str, Any]] = []
    suggested_locales: list[str] = []
    suggested_outputs: list[str] = []

    for block in blocks:
        if block.get("type") == "heading":
            level = int(block.get("metadata", {}).get("level", len(heading_stack) + 1) or 1)
            heading_text = normalize_text(block.get("text"))
            heading_stack = heading_stack[: max(level - 1, 0)]
            heading_stack.append(heading_text)
            context["heading_hint"] = heading_text
            if not context.get("screen"):
                screen_hint = pick_screen_from_headings(heading_stack)
                if screen_hint:
                    context["screen"] = screen_hint
            continue

        inferred = infer_structured_candidate(block, artifact, context)
        if inferred:
            entries.append(inferred)
            continue

        context["heading_hint"] = heading_stack[-1] if heading_stack else ""
        if not context.get("screen"):
            screen_hint = pick_screen_from_headings(heading_stack)
            if screen_hint:
                context["screen"] = screen_hint
        block_entries, locales, outputs = infer_candidate_from_text(block, artifact, context)
        for locale in locales:
            if locale not in suggested_locales:
                suggested_locales.append(locale)
        for output in outputs:
            if output not in suggested_outputs:
                suggested_outputs.append(output)
        entries.extend(block_entries)

        if block.get("type") == "paragraph":
            text = normalize_text(block.get("text"))
            if len(text) <= 160 and not looks_copy_label(text) and text.lower() not in AMBIGUOUS_LABELS:
                if any(token in text.lower() for token in ["shown", "toast", "用户", "after", "when", "点击", "shown after", "displayed"]):
                    context["background"] = text

    return entries, suggested_locales, suggested_outputs


def main() -> int:
    args = parse_args()
    source_path = Path(args.source).expanduser()
    evidence = load_json(source_path)

    bucket: dict[tuple[str, str, str, str], dict[str, Any]] = {}
    suggested_locales: list[str] = []
    suggested_outputs: list[str] = []

    for artifact in evidence.get("artifacts", []):
        artifact_entries, locales, outputs = extract_from_artifact(artifact)
        for entry in artifact_entries:
            merge_candidate(bucket, entry)
        for locale in locales:
            if locale not in suggested_locales:
                suggested_locales.append(locale)
        for output in outputs:
            if output not in suggested_outputs:
                suggested_outputs.append(output)

    entries = list(bucket.values())
    payload = {
        "schema_version": "1.0",
        "created_at": now_iso(),
        "source_locale": evidence.get("source_locale") or "en",
        "suggested_target_locales": suggested_locales,
        "suggested_target_outputs": suggested_outputs,
        "entries": entries,
        "summary": {
            "artifact_count": len(evidence.get("artifacts", [])),
            "candidate_count": len(entries),
            "suggested_target_locales": suggested_locales,
            "suggested_target_outputs": suggested_outputs,
        },
    }

    output_path = Path(args.output).expanduser()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote copy candidates to {output_path}")
    print(json.dumps(payload["summary"], ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
